/**
 * Generate cursor assets module
 *
 * Reads SVG files from assets/interactions/ and generates a TypeScript module
 * with inlined SVG content for use as cursors. This avoids runtime fetch calls.
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ASSETS_DIR = "assets/interactions";
const OUTPUT_FILE = "shared/cursor-assets.ts";

interface CursorAsset {
  mode: string;
  path: string;
  outputKey: string;
}

const CURSOR_ASSETS: CursorAsset[] = [
  {
    mode: "food:basic",
    path: "food/basic-active.svg",
    outputKey: "FOOD_BASIC",
  },
  {
    mode: "food:fancy",
    path: "food/fancy-active.svg",
    outputKey: "FOOD_FANCY",
  },
  {
    mode: "water",
    path: "water/active.svg",
    outputKey: "WATER",
  },
  {
    mode: "yarn",
    path: "toys/yarn-active.svg",
    outputKey: "YARN",
  },
];

function generateCursorAssets() {
  console.log("📦 Generating cursor assets module...\n");

  const svgContents: Record<string, string> = {};

  // Read all SVG files
  for (const asset of CURSOR_ASSETS) {
    const fullPath = join(ASSETS_DIR, asset.path);
    try {
      let svgContent = readFileSync(fullPath, "utf-8");

      // Clean up SVG (remove extra whitespace, newlines)
      svgContent = svgContent
        .trim()
        .replace(/\s+/g, " ")
        .replace(/> </g, "><");

      svgContents[asset.outputKey] = svgContent;
      console.log(`✓ Loaded: ${asset.path}`);
    } catch (error) {
      console.error(`✗ Failed to load ${fullPath}:`, error);
      process.exit(1);
    }
  }

  // Generate TypeScript module
  const tsContent = `/**
 * Cursor Assets - Auto-generated SVG content for cursors
 * 
 * Generated by scripts/generate-cursor-assets.ts
 * DO NOT EDIT MANUALLY
 */

export type CursorMode = "food:basic" | "food:fancy" | "water" | "yarn";

/**
 * SVG content for each cursor mode
 */
export const CURSOR_SVG_CONTENT: Record<CursorMode, string> = {
  "food:basic": \`${svgContents.FOOD_BASIC}\`,
  "food:fancy": \`${svgContents.FOOD_FANCY}\`,
  water: \`${svgContents.WATER}\`,
  yarn: \`${svgContents.YARN}\`,
};

/**
 * Convert SVG content to data URL for cursor usage
 */
export function svgToDataUrl(svgContent: string): string {
  const base64 = btoa(svgContent);
  return \`data:image/svg+xml;base64,\${base64}\`;
}

/**
 * Get data URL for a cursor mode
 */
export function getCursorDataUrl(mode: CursorMode): string {
  return svgToDataUrl(CURSOR_SVG_CONTENT[mode]);
}
`;

  // Write output file
  writeFileSync(OUTPUT_FILE, tsContent, "utf-8");
  console.log(`\n📦 Generated: ${OUTPUT_FILE}`);
  console.log(`   Included ${CURSOR_ASSETS.length} cursor assets\n`);
}

// Run the script
generateCursorAssets();
