/**
 * Generate interaction SVG assets module
 *
 * Reads SVG files and generates a TypeScript module with the content
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ASSETS_DIR = "assets/interactions";
const OUTPUT_FILE = "shared/interaction-svgs.ts";

const SVG_FILES = [
  { key: "foodBasic", path: "food/basic-default.svg" },
  { key: "foodBasicActive", path: "food/basic-active.svg" },
  { key: "foodFancy", path: "food/fancy-default.svg" },
  { key: "foodFancyActive", path: "food/fancy-active.svg" },
  { key: "water", path: "water/default.svg" },
  { key: "waterActive", path: "water/active.svg" },
  { key: "laser", path: "toys/laser-pointer-default.svg" },
  { key: "laserActive", path: "toys/laser-pointer-active.svg" },
  { key: "yarn", path: "toys/yarn-default.svg" },
  { key: "yarnActive", path: "toys/yarn-active.svg" },
];

function generateInteractionSvgs() {
  console.log("📦 Generating interaction SVG assets module...\n");

  const svgContents: Record<string, string> = {};

  // Read all SVG files
  for (const asset of SVG_FILES) {
    const fullPath = join(ASSETS_DIR, asset.path);
    try {
      let svgContent = readFileSync(fullPath, "utf-8");

      // Clean up SVG (remove extra whitespace, newlines)
      svgContent = svgContent
        .trim()
        .replace(/\s+/g, " ")
        .replace(/> </g, "><");

      svgContents[asset.key] = svgContent;
      console.log(`✓ Loaded: ${asset.path}`);
    } catch (error) {
      console.error(`✗ Failed to load ${fullPath}:`, error);
      process.exit(1);
    }
  }

  // Generate TypeScript module
  const entries = SVG_FILES.map(
    (asset) => `  ${asset.key}: \`${svgContents[asset.key]}\`,`
  ).join("\n");

  const tsContent = `/**
 * Interaction SVG Assets
 * 
 * Auto-generated by scripts/generate-interaction-svgs.ts
 * DO NOT EDIT MANUALLY
 * 
 * Centralized exports for all interaction SVG assets.
 * These match the files in assets/interactions/
 * Each interaction has both a default and active state.
 */

export const INTERACTION_SVGS = {
${entries}
} as const;

export type InteractionSvgKey = keyof typeof INTERACTION_SVGS;
`;

  writeFileSync(OUTPUT_FILE, tsContent, "utf-8");
  console.log(`\n✅ Generated: ${OUTPUT_FILE}`);
}

generateInteractionSvgs();
