/**
 * Cursor Assets - Auto-generated SVG content for cursors
 * 
 * Generated by scripts/generate-cursor-assets.ts
 * DO NOT EDIT MANUALLY
 */

export type CursorMode = "food:basic" | "food:fancy" | "water" | "yarn";

/**
 * SVG content for each cursor mode
 */
export const CURSOR_SVG_CONTENT: Record<CursorMode, string> = {
  "food:basic": `<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><!-- Kibble bag --><rect x="16" y="12" width="32" height="40" rx="2" fill="#8B4513"/><rect x="16" y="12" width="32" height="8" fill="#A0522D"/><!-- Bag fold at top --><path d="M 20 12 L 20 8 L 24 12 Z" fill="#654321"/><path d="M 44 12 L 44 8 L 40 12 Z" fill="#654321"/><!-- Label area --><rect x="20" y="22" width="24" height="20" rx="2" fill="#F5DEB3"/><!-- Kibble pieces on label --><circle cx="26" cy="28" r="2" fill="#8B4513"/><circle cx="32" cy="30" r="2" fill="#A0522D"/><circle cx="38" cy="28" r="2" fill="#8B4513"/><circle cx="29" cy="34" r="2" fill="#654321"/><circle cx="35" cy="36" r="2" fill="#A0522D"/><!-- Brand text suggestion lines --><rect x="22" y="44" width="20" height="2" rx="1" fill="#8B4513" opacity="0.5"/><rect x="22" y="48" width="16" height="2" rx="1" fill="#8B4513" opacity="0.5"/></svg>`,
  "food:fancy": `<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><!-- Tuna can body --><ellipse cx="32" cy="38" rx="18" ry="5" fill="#C0C0C0"/><rect x="14" y="22" width="36" height="16" fill="#D3D3D3"/><ellipse cx="32" cy="22" rx="18" ry="5" fill="#E8E8E8"/><!-- Can ridges --><line x1="14" y1="26" x2="50" y2="26" stroke="#A9A9A9" stroke-width="0.5"/><line x1="14" y1="30" x2="50" y2="30" stroke="#A9A9A9" stroke-width="0.5"/><line x1="14" y1="34" x2="50" y2="34" stroke="#A9A9A9" stroke-width="0.5"/><!-- Label --><rect x="18" y="24" width="28" height="12" rx="1" fill="#FFD700"/><!-- Fish icon on label --><path d="M 28 30 L 32 28 L 36 30 L 34 32 L 32 31 L 30 32 Z" fill="#FF6347"/><circle cx="33" cy="29" r="0.5" fill="#000000"/><!-- Decorative waves --><path d="M 20 32 Q 24 31 28 32" stroke="#FFA500" stroke-width="1" fill="none"/><path d="M 36 32 Q 40 31 44 32" stroke="#FFA500" stroke-width="1" fill="none"/><!-- Pull tab --><ellipse cx="32" cy="22" rx="4" ry="2" fill="#B8B8B8"/><rect x="30" y="18" width="4" height="4" rx="1" fill="#A9A9A9"/></svg>`,
  water: `<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><!-- Water droplet --><defs><linearGradient id="waterGradient" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" style="stop-color:#87CEEB;stop-opacity:1" /><stop offset="100%" style="stop-color:#4682B4;stop-opacity:1" /></linearGradient></defs><!-- Main droplet shape --><path d="M 32 12 Q 42 26 42 36 Q 42 46 32 46 Q 22 46 22 36 Q 22 26 32 12 Z" fill="url(#waterGradient)"/><!-- Highlight shine --><ellipse cx="28" cy="24" rx="4" ry="6" fill="#FFFFFF" opacity="0.5"/><ellipse cx="30" cy="30" rx="2" ry="3" fill="#FFFFFF" opacity="0.3"/><!-- Secondary small highlight --><circle cx="36" cy="32" r="2" fill="#FFFFFF" opacity="0.4"/><!-- Shadow/depth at bottom --><ellipse cx="32" cy="42" rx="8" ry="3" fill="#000000" opacity="0.1"/></svg>`,
  yarn: `<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><!-- Yarn ball --><defs><linearGradient id="yarnGradient" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" style="stop-color:#FF69B4;stop-opacity:1" /><stop offset="50%" style="stop-color:#FF1493;stop-opacity:1" /><stop offset="100%" style="stop-color:#C71585;stop-opacity:1" /></linearGradient></defs><!-- Main yarn ball --><circle cx="32" cy="32" r="18" fill="url(#yarnGradient)"/><!-- Yarn strand wrappings --><path d="M 20 26 Q 26 24 32 26 Q 38 28 44 26" fill="none" stroke="#FF1493" stroke-width="2" opacity="0.8"/><path d="M 18 32 Q 24 30 32 32 Q 40 34 46 32" fill="none" stroke="#FF1493" stroke-width="2" opacity="0.8"/><path d="M 20 38 Q 26 36 32 38 Q 38 40 44 38" fill="none" stroke="#FF1493" stroke-width="2" opacity="0.8"/><!-- Diagonal wrappings --><path d="M 26 18 Q 30 24 32 32 Q 34 40 38 46" fill="none" stroke="#C71585" stroke-width="1.5" opacity="0.7"/><path d="M 38 18 Q 34 24 32 32 Q 30 40 26 46" fill="none" stroke="#C71585" stroke-width="1.5" opacity="0.7"/><!-- Circular wrappings for texture --><circle cx="32" cy="32" r="14" fill="none" stroke="#FF69B4" stroke-width="1.5" opacity="0.5"/><circle cx="32" cy="32" r="10" fill="none" stroke="#FF1493" stroke-width="1" opacity="0.6"/><!-- Loose strand at top --><path d="M 32 14 Q 28 10 26 8 Q 24 6 24 4" fill="none" stroke="#FF1493" stroke-width="2" stroke-linecap="round"/><!-- Shadow --><ellipse cx="32" cy="50" rx="16" ry="3" fill="#000000" opacity="0.2"/><!-- Highlights for dimension --><circle cx="26" cy="26" r="4" fill="#FFFFFF" opacity="0.3"/><circle cx="38" cy="28" r="2" fill="#FFFFFF" opacity="0.2"/></svg>`,
};

/**
 * Convert SVG content to data URL for cursor usage
 */
export function svgToDataUrl(svgContent: string): string {
  const base64 = btoa(svgContent);
  return `data:image/svg+xml;base64,${base64}`;
}

/**
 * Get data URL for a cursor mode
 */
export function getCursorDataUrl(mode: CursorMode): string {
  return svgToDataUrl(CURSOR_SVG_CONTENT[mode]);
}
